version: '3'

services:
  portainer:
    container_name: portainer
    stdin_open: true
    tty: true
    image: portainer/portainer
    restart: always
    ports:
      - "9000:9000/tcp"
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./hassio:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
